In [1]:
import os, sys
PWD = os.getenv('PWD')
os.chdir(PWD)
sys.path.insert(0, os.getenv('PWD'))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "local_settings.py")
import django
django.setup()
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"

from datetime import datetime, timedelta
from pandas import DataFrame, to_datetime, set_option
from TpsParse.Tps.TpsFile import TpsFile
import os
from numpy import quantile, nan
from math import ceil
from math import pi
import pandas as pd

set_option('display.max_columns', 500)
set_option('display.max_row', 2000)

from bokeh.resources import CDN
from bokeh.embed import components
from bokeh.models import Range1d, NumeralTickFormatter, ColumnDataSource, FactorRange, HoverTool
from bokeh.plotting import figure
from bokeh.transform import linear_cmap, factor_cmap, cumsum
from bokeh.io import show, output_notebook
from bokeh.palettes import Category20_20

from django.db.models import Sum, DateField
from django.db.models.functions import Trunc
from Utils.clean_string import clean_string

output_notebook()

In [2]:
from app.models import Ventas, Items, Movimpu, Imputaci, Movgan, MovSilos, MovProd, Cajas, Gf, Giros, \
Cobrados, CtaCte, MovCons, MovLeche, Pagados, VctaCte, GanCar, Acumula, Actividad

In [3]:
# Obtener código de imputaciones
df2 = DataFrame(Imputaci.objects.values('codigo'))
df2.codigo.tolist()

[35,
 36,
 37,
 38,
 39,
 123,
 124,
 125,
 126,
 127,
 566,
 841,
 842,
 843,
 273,
 274,
 275,
 276,
 277,
 24,
 25,
 26,
 27,
 28,
 29,
 31,
 32,
 33,
 34,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 80,
 81,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 1325,
 1326,
 1327,
 1328,
 1329,
 1330,
 1331,
 1332,
 1333,
 1334,
 1335,
 1336,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 1186,
 1189,
 1193,
 1194,
 1195,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 664,
 665,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 1387,
 1388,
 1389,
 1390,
 1391,
 1392,
 1393,
 1394,
 1395,
 1396,
 1397,
 1398,
 1229,
 1230,
 1231,
 1232,
 1233,
 1234,
 1235,
 1236,
 1237,
 1238,
 1239,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 614,
 615,
 616,
 617,
 618,
 619,
 621,
 622,
 623,
 624,
 626,
 628,
 630,
 1047,
 1048,
 1049,
 1051,
 1052,
 1053,
 1054,
 1055,
 1056,
 1057,
 1058,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 530,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 51,
 52,
 53,
 1352,
 1353,
 1354,
 1355,
 1356,
 1357,
 1358,
 1359,
 1360,
 1361,
 1362,
 1363,
 1364,
 1365,
 1366,
 1367,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 1240,
 1241,
 1242,
 1243,
 1244,
 1245,
 1246,
 1247,
 1248,
 1249,
 1250,
 1251,
 1252,
 1310,
 1311,
 1312,
 1313,
 1314,
 1315,
 1316,
 1317,
 1318,
 1319,
 1320,
 1321,
 1322,
 1323,
 1324,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 1035,
 1036,
 1037,
 1038,
 1039,
 1040,
 1041,
 1042,
 1043,
 1044,
 1045,
 1046,
 631,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 648,
 649,
 650,
 651,
 652,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 583,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 1059,
 1060,
 1061,
 1062,
 1063,
 1064,
 1065,
 1066,
 1067,
 1068,
 1069,
 1070,
 1071,
 1072,
 1073,
 1074,
 1075,
 1076,
 1077,
 1078,
 1079,
 1080,
 1081,
 1082,
 1084,
 1085,
 1086,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 1018,
 1019,
 1020,
 1021,
 1022,
 1023,
 1024,
 1025,
 1026,
 1027,
 1028,
 1029,
 1030,
 1031,
 1032,
 1033,
 1034,
 1087,
 1088,
 1089,
 1090,
 1091,
 1092,
 1093,
 1094,
 1095,
 1096,
 1097,
 1098,
 1099,
 1100,
 1101,
 1102,
 1103,
 1104,
 1105,
 1106,
 1107,
 1108,
 1109,
 1111,
 1112,
 1113,
 1114,
 1115,
 1116,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 1117,
 1118,
 1119,
 1120,
 1122,
 1123,
 1124,
 1125,
 1126,
 1127,
 1128,
 1129,
 1130,
 1131,
 770,
 771,
 772,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 713,
 1171,
 1172,
 1173,
 1174,
 1175,
 1176,
 1177,
 1178,
 1179,
 1180,
 1181,
 1182,
 1183,
 1198,
 1199,
 1200,
 1201,
 1202,
 1203,
 1204,
 1205,
 1206,
 1207,
 1208,
 1209,
 1210,
 1211,
 1212,
 1187,
 1188,
 1190,
 1191,
 1192,
 1170,
 1184,
 1213,
 1214,
 1215,
 1216,
 1217,
 1218,
 1219,
 1220,
 1221,
 1222,
 1223,
 1224,
 1225,
 1226,
 1227,
 1228,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 1253,
 1254,
 1255,
 1256,
 1257,
 1258,
 1259,
 1260,
 1261,
 1262,
 1263,
 1264,
 1265,
 1266,
 1267,
 1268,
 1269,
 1270,
 1271,
 1272,
 1273,
 1274,
 1275,
 1276,
 1277,
 1278,
 1279,
 1280,
 1281,
 1282,
 1283,
 1284,
 1285,
 1286,
 1287,
 1288,
 1289,
 1290,
 1291,
 1292,
 1293,
 1294,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 1337,
 1338,
 1339,
 1340,
 1341,
 1342,
 1343,
 1344,
 1345,
 1346,
 1347,
 1348,
 1349,
 1350,
 1351,
 1295,
 1296,
 1297,
 1298,
 1299,
 1300,
 1301,
 1302,
 1303,
 1304,
 1305,
 1306,
 1307,
 1308,
 1309,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 1413,
 ...]

In [4]:
# Obtener los códigos de imputación que no existen.
df1 = DataFrame(Movimpu.objects.values('cod_imput').distinct('cod_imput'))
df1.dropna(inplace=True)
df1 = df1.astype({'cod_imput': int})
df1[~df1.cod_imput.isin(df2.codigo.tolist())].cod_imput.tolist()

[]

In [5]:
df = DataFrame(Acumula.objects.values())
df.dropna(subset=['descripcion'], inplace=True)
df.descripcion

0                          Cadenas
1                     Extractotres
2                Sistema Aireación
3              Gastos Banco Mutual
4               Compra Maquinarias
5                          Sanidad
6                         Quinchos
7                          Aguadas
8                      Inoculantes
9                          Secadas
10                           Pagos
11                       Cobranzas
12                 Reposicion Caja
13                        Facturas
14                         Balanza
15                       Fungicida
16                         Tanques
17                      Comisiones
18                       Subsidios
19                          Cursos
20                         Pellets
21                         Tambo 2
22                       Movilidad
23                Compra Camioneta
24                            Moto
25                      Descuentos
26            Diferencia De Cambio
27            Pintura Herramientas
28                     Computación
29                Sellador Pezones
30             Servicio Ordeñadora
31                      Jubilación
32                       Mangueras
33               Bolilleros Varios
34                         Vidrios
35                      Sanitarios
36                        Semillas
37                         Cosecha
38                     Lubricantes
39                      Neumàticos
40                         Seguros
41                          Bolsas
42                          Aceite
43                            Maíz
44                      Pinturería
45                         Escapes
46                           Silos
47                           Lonas
48                Limpieza Semilla
49         Materiales Construcción
50              Mototes Eléctricos
51                    Electricidad
52                        Teléfono
53                         Caballo
54                    Herramientas
55                      Reparación
56                             Luz
57                          Ventas
58                     Veterinaria
59     Repuest. Y Repar. Vehículos
60                    Agroquímicos
61                         Hierros
62                        Tornería
63                      Alquileres
64                    Concentrados
65                       Intereses
66                      Escribanía
67              Alambrado Olímpico
68                Motor Hidráulico
69                     Maquinarias
70                          Varios
71                           Caños
72                      Engranajes
73                Cosecha Terceros
74                        Hacienda
75                  Fotos Terneras
76                      Hidráulica
77               Bombas Sumergible
78                         Retenes
79                  Alimento Vacas
80                         Retiros
81               Aportes Empleados
82                     Forestación
83                         Alarmas
84                        Analisis
85                        Regalías
86                    Refrigerante
87           Indumentaria Personal
88               Premios Empleados
89                         Casilla
90                     Rodamientos
91                     Formularios
92                     Refacciones
93                Siembra Terceros
94                    Curasemillas
95                       Servicios
96                        Creditos
97                   Gastos Acopio
98                         Rodados
99                       Comederos
100          Alineación Y Balanceo
101                        Boyeros
102                     Accesorios
103                 Limpieza Canal
104                         Fletes
105                        Filtros
106                        Correas
107                Hilo Arroladora
108                   Reproducción
109                          Tambo
110                      Impuestos
111                   Combustibles
112                  Fertilizantes
113                     Transporte
114                        Sueldos
115                       Corralón
116                           Soja
117       Venta Maquinarias Usadas
118                    Venta Leche
119                     Ferretería
120                     Honorarios
121                     Balanceado
122                            Gas
123                      Repuestos
124                        Molinos
125               Produc. Limpieza
126                Grupo Clucellas
127                Control Lechero
128                         Veneno
Name: descripcion, dtype: object

In [6]:
df = DataFrame(Actividad.objects.values())
df

   nro_actividad  descripcion
0              1        Mixta
1              2        Tambo
2              3  Agricultura

In [7]:
DataFrame(DataFrame(Movimpu.objects.values('tipo_movim', 'cod_imput__descripcion', 'actividad')).groupby(['tipo_movim']))

,0,1
0,Cobranza,tipo_movim cod_imput__descripci...
1,Documento De Contado,tipo_movim cod_imput__de...
2,Egreso,tipo_movim cod_imput__descripcion activ...
3,Facturas Cuenta Corriente,tipo_movim cod_imput__d...
4,Facturas De Contado,tipo_movim cod_imput__desc...
5,Ingreso,tipo_movim cod_imput__descripcion activ...
6,Nota De Crédito,tipo_movim cod_imput__descripcion...
7,Nota De Crédito,tipo_movim cod_imput__des...
8,Nota De Crédito Emitida,tipo_movim cod_imput__des...
9,Nota De Débito,tipo_movim cod_imput__desc...
10,Nota De Débito Emitida,tipo_movim cod_imput__descr...
11,Orden De Pago,tipo_movim cod_imput__descripcion a...
12,Ventas Cuenta Corriente,tipo_movim cod_im...
13,Ventas De Contado,tipo_movim cod_imput__descripcio...

In [8]:
acumuladores_ingreso = [
    'Cobranza', 'Ingreso', 'Ventas Cuenta Corriente', 'Ventas De Contado', 'Nota De Crédito', 'Nota De Débito Emitida'
]
acumuladores_egreso = [
    'Documento De Contado', 'Egreso', 'Facturas De Contado', 'Facturas Cuenta Corriente', 'Orden De Pago', 'Nota De Crédito Emitida', 'Nota De Débito'
]

In [9]:
movimpu_df = DataFrame(Movimpu.objects.values(
        'cod_imput__descripcion',
        'cod_imput__donde_acumula__descripcion',
        'actividad__descripcion', 'importe',
        'tipo_movim'))
movimpu_df.rename(columns={
    'cod_imput__descripcion': 'imputacion',
    'cod_imput__donde_acumula__descripcion': 'acumulador',
}, inplace=True); movimpu_df

,imputacion,acumulador,actividad__descripcion,importe,tipo_movim
0,None,None,None,12759.60,Egreso
1,Cosechadora Sts 9650,Maquinarias,None,0.00,Ventas De Contado
2,Cosechadora Sts 9650,Maquinarias,None,0.00,Ventas De Contado
3,Cosechadora Sts 9650,Maquinarias,None,0.00,Ventas De Contado
4,Cosechadora Sts 9650,Maquinarias,None,0.00,Ventas De Contado
...,...,...,...,...,...
56549,Ferretería,Ferretería,None,6734.40,Facturas Cuenta Corriente
56550,Ferretería,Ferretería,None,7276.33,Facturas Cuenta Corriente
56551,Pago Proveedores,None,None,16952.98,Orden De Pago
56552,Pago Proveedores,None,None,38789.56,Orden De Pago
56553,Comida Campo,Varios,None,14187.52,Facturas Cuenta Corriente

In [10]:
movimpu_df.loc[movimpu_df.tipo_movim.isin(acumuladores_ingreso), 'tipo'] = 'Ingreso'
movimpu_df.loc[movimpu_df.tipo_movim.isin(acumuladores_egreso), 'tipo'] = 'Egreso'
movimpu_df.loc[movimpu_df.acumulador == 'Ventas', 'tipo'] = 'Ingreso'
movimpu_df.dropna(subset=['tipo'], inplace=True)
movimpu_df

,imputacion,acumulador,actividad__descripcion,importe,tipo_movim,tipo
0,None,None,None,12759.60,Egreso,Egreso
1,Cosechadora Sts 9650,Maquinarias,None,0.00,Ventas De Contado,Ingreso
2,Cosechadora Sts 9650,Maquinarias,None,0.00,Ventas De Contado,Ingreso
3,Cosechadora Sts 9650,Maquinarias,None,0.00,Ventas De Contado,Ingreso
4,Cosechadora Sts 9650,Maquinarias,None,0.00,Ventas De Contado,Ingreso
...,...,...,...,...,...,...
56549,Ferretería,Ferretería,None,6734.40,Facturas Cuenta Corriente,Egreso
56550,Ferretería,Ferretería,None,7276.33,Facturas Cuenta Corriente,Egreso
56551,Pago Proveedores,None,None,16952.98,Orden De Pago,Egreso
56552,Pago Proveedores,None,None,38789.56,Orden De Pago,Egreso
56553,Comida Campo,Varios,None,14187.52,Facturas Cuenta Corriente,Egreso

In [11]:
DataFrame(movimpu_df.groupby(['actividad__descripcion','tipo', 'acumulador']).sum())

                                                   importe
actividad__descripcion tipo    acumulador
Agricultura            Ingreso Hacienda           20986.13
                               Maquinarias            0.00
                               Ventas          12410315.60
Mixta                  Ingreso Fletes                 0.00
                               Maquinarias            0.00
Tambo                  Egreso  Alimento Vacas      1467.40
                               Sueldos             1483.18
                       Ingreso Maquinarias            0.00

In [153]:
venta_ganado = ['Ventas Animales', 'Venta De Hacienda I']
venta_tambo = ['Venta De Leche']
venta_agriculura = ['Ventas De Cereales']

impu_ganado = ['Crianza I', 'Flete Ganaderia', 'Gastos Ganaderia', 'Gastos Veterinaria', 
                       'Suplementación I', 'Suplementación Recría', 'Compra Hacienda']

impu_agriculura = ['Agroquimicos', 'Combustible', 'Fertilizantes', 'Flete Agricultura', 
                       'Gastos Varios Maquinaria', 'Inoculantes', 'Insumos De Semillas',
                      'Lubricante Maquinaria', 'Mixer', 'Personal Maquinaria', 'Reparación Tractores',
                      'Semillas', 'Silos', 'Rollos', 'Gastos De Forraje']

impu_tambo = ['Control Lechero', 'Energía Tambo', 'Higiene Tambo', 'Higiene Tambo I', 
                    'Honorarios Tambero', 'Ordeñadora I', 'Otros Gastos Tambo', 'Sanidad Tambo',
                   'Suplementación Tambo', 'Suplementación Guachera']

imputaciones = ['Crianza I', 'Flete Ganaderia', 'Gastos Ganaderia', 'Gastos Veterinaria', 
                       'Suplementación I', 'Suplementación Recría', 'Compra Hacienda', 'Agroquimicos', 'Combustible', 'Fertilizantes', 'Flete Agricultura', 
                       'Gastos Varios Maquinaria', 'Inoculantes', 'Insumos De Semillas',
                      'Lubricante Maquinaria', 'Mixer', 'Personal Maquinaria', 'Reparación Tractores',
                      'Semillas', 'Silos', 'Rollos', 'Gastos De Forraje', 'Control Lechero', 'Energía Tambo', 'Higiene Tambo', 'Higiene Tambo I', 
                    'Honorarios Tambero', 'Ordeñadora I', 'Otros Gastos Tambo', 'Sanidad Tambo',
                   'Suplementación Tambo', 'Suplementación Guachera']
imputacion_ventas = ['Ventas Animales', 'Venta De Hacienda I', 'Venta De Leche', 'Ventas De Cereales']

imputacion_ganado = ['Crianza I', 'Flete Ganaderia', 'Gastos Ganaderia', 'Gastos Veterinaria', 
               'Suplementación I', 'Suplementación Recría', 'Compra Hacienda', 
               'Ventas Animales', 'Venta De Hacienda I']

imputacion_agriculura = ['Agroquimicos', 'Combustible', 'Fertilizantes', 'Flete Agricultura', 
                   'Gastos Varios Maquinaria', 'Inoculantes', 'Insumos De Semillas',
                   'Lubricante Maquinaria', 'Mixer', 'Personal Maquinaria', 'Reparación Tractores',
                   'Semillas', 'Silos', 'Rollos', 'Gastos De Forraje', 'Ventas De Cereales']

imputacion_tambo = ['Control Lechero', 'Energía Tambo', 'Higiene Tambo', 'Higiene Tambo I', 'Honorarios Tambero', 
              'Ordeñadora I', 'Otros Gastos Tambo', 'Sanidad Tambo', 'Suplementación Tambo', 
              'Suplementación Guachera', 'Venta De Leche']

In [66]:
movimpu.loc[movimpu.imputacion_acumulada.isin(imputaciones), 'tipo'] = 'Costos'
movimpu.loc[movimpu.imputacion_acumulada.isin(impu_ventas), 'tipo'] = 'Ventas'

ganado = movimpu.loc[movimpu.imputacion_acumulada
    .isin(impu_ganado)].copy()
agricultura = movimpu.loc[movimpu.imputacion_acumulada
    .isin(impu_agriculura)].copy()
tambo = movimpu.loc[movimpu.imputacion_acumulada
    .isin(impu_tambo)].copy()

rentabilidad = {
    'ganado': ganado,
    'agricultura': agricultura,
    'tambo': tambo,
}

In [39]:
gb = DataFrame(movimpu.groupby('cod_imput__donde_acumula__descripcion').importe.sum()); gb

                                           importe
cod_imput__donde_acumula__descripcion
Agroquimicos                            2068319.19
Ajustes                                  109759.50
Arrendamientos                          1044376.50
Asesor Contable                          234250.00
Asesor Tecnico                            16000.00
Bonificaciones                            55245.06
Cobranzas                              57101472.36
Combustible                              658631.12
Comite De Cuenca                         148808.13
Compra Hacienda                           76000.00
Control Lechero                           99900.00
Crianza I                                 30190.55
Energía Estructura                       153426.07
Energía Tambo                            216739.48
Fertilizantes                             72246.30
Flete Agricultura                        784108.23
Flete Ganaderia                            2322.56
Fletes                                   278098.08
Gastos Bancarios                        1216307.81
Gastos De Estructura                       6595.00
Gastos De Forraje                        358696.50
Gastos De Oficina                         11776.67
Gastos De Ventas 1                          500.79
Gastos Ganaderia                          53902.52
Gastos Generales                         843713.33
Gastos No Imputables                    1949656.55
Gastos Varios Maquinaria                   4323.00
Gastos Veterinaria                       877331.66
Higiene Tambo                            253210.87
Higiene Tambo I                           13953.44
Honorarios                              9861668.32
Honorarios Administrativos              1981538.00
Honorarios Tambero                      3815267.71
Impuestos Generales                      711211.43
Impuestos Nacionales                     423547.24
Inoculantes                               87085.26
Insumos De Semillas                        8530.00
Intereses                                120971.18
Inversiones Administración                31500.00
Inversiones Estructura                    17959.67
Labores Contratados                     1730618.06
Lubricante Maquinaria                     19841.79
Mantenimiento De Equipos                 176440.53
Mixer                                      1276.00
Ordeñadora I                             292748.05
Otros Gastos Tambo                         3576.81
Pago A Proveedores                     52644071.02
Personal Estructura                         662.56
Personal Maquinaria                        3286.69
Reparacion Maquinas Comunes              160785.83
Reparación Tractores                      64926.07
Retiros                                 5217000.00
Rollos                                    28952.48
Sanidad I                                 20642.56
Sanidad Tambo                            263428.38
Seguros                                  121261.72
Semillas                                4109564.20
Servicios De Planta                      145985.55
Servicios Propios                            22.00
Servicos Contratados                    3446144.69
Silos                                    503734.70
Suplementación Guachera                   12050.15
Suplementación I                         797693.41
Suplementación Recría                   1171186.64
Suplementación Tambo                   12049552.03
Vehículos De Administración               83878.69
Vehículos De Estructura                   51172.85
Venta De Hacienda I                     8804094.25
Venta De Leche                         50471220.64
Ventas Animales                          281037.43
Ventas De Cereales                      6335995.23

In [41]:
costos = movimpu[movimpu.cod_imput__donde_acumula__descripcion.isin(imputacion_animales)].importe.sum()

In [42]:
ventas = movimpu[movimpu.cod_imput__donde_acumula__descripcion.isin(
    venta_animales)].importe.sum(); ventas

9085131.680000002

##### Filtrar los datos del año 2017

In [36]:
df = df[(df.periodo_contable >= '01/01/2017') & (df.periodo_contable <= '12/31/2017')]; df

,imputacion_simple,imputacion_acumulada,periodo_contable,tipo_movim,importe,actividad,tipo
8511,Aceites,Combustible,2017-01-01,Facturas De Contado,667.77,None,Egreso
8512,Vacunacion,Insumos Ganaderia,2017-01-01,Facturas De Contado,237.00,None,Egreso
8513,Nafta,Combustible,2017-01-01,Facturas De Contado,494.70,None,Egreso
8514,Gas,Combustible,2017-01-01,Facturas De Contado,156.20,None,Egreso
8515,Repuestos Y Reparaciones,Mantenimiento,2017-01-01,Facturas De Contado,850.00,None,Egreso
...,...,...,...,...,...,...,...
9587,Seguros Accidentes Personales,Seguros,2017-06-30,Facturas Cuenta Corriente,28.00,None,Egreso
9588,Intereses Creditos,Creditos,2017-06-30,Facturas Cuenta Corriente,5448.19,None,Egreso
9589,Intereses Creditos,Creditos,2017-06-30,Facturas Cuenta Corriente,8950.11,None,Egreso
9590,Repuestos Y Reparaciones,Mantenimiento,2017-06-30,Facturas Cuenta Corriente,6244.35,None,Egreso
9591,Deudores Por Ventas,Administracion,2017-11-30,Cobranza,6310.00,None,Ingreso

Movimientos de Combustible

In [3]:
mov_cons = DataFrame(MovCons.objects.values('fecha', 'nro_comprob', 'ing_egr', 'costo')); mov_cons

        fecha  nro_comprob  ing_egr  costo
0  2020-03-09            1        1    1.0
1  2020-03-09           12        1    1.0
2  2020-03-09          111        2  451.0
3  2020-03-09           11        2    1.0

In [4]:
gb = DataFrame(mov_cons.groupby(['ing_egr']).costo.sum()); gb

         costo
ing_egr
1          2.0
2        452.0

Movimientos de Caja

In [5]:
gf = DataFrame(Gf.objects.values('n_comp', 'fecha', 'i_o_e', 'importe')); gf

      n_comp       fecha  i_o_e   importe
0      11708  2018-06-20      2   90000.0
1      11709  2018-06-20      2   90000.0
2      11710  2018-07-20      2   90000.0
3      11711  2018-07-20      2   90000.0
4      11712  2018-08-20      2   90000.0
5      11713  2018-08-20      2   90000.0
6   75576767  2018-09-29      1   50000.0
7   75576768  2018-09-29      1   25000.0
8   75576769  2018-09-29      1   25000.0
9      72019  2019-08-02      2  150000.0
10     72020  2020-03-09      1      10.0

In [6]:
gb = DataFrame(gf.groupby(['i_o_e']).importe.sum()); gb

        importe
i_o_e
1      100010.0
2      690000.0

Movimientos de Productos

In [7]:
items = DataFrame(Items.objects.values('fecha','nro_comprobante', 'movimiento', 
                                       'nro_producto__nro_linea__nombre')); items

        fecha  nro_comprobante  movimiento nro_producto__nro_linea__nombre
0  2019-06-26            89766           1                         Semilla
1  2020-03-09               12           1                         Semilla
2  2019-06-26            89766           1                       Silobolsa
3  2020-03-09              111           1                       Silobolsa
4  2020-03-09                1           1                       Silobolsa
5  2019-06-26            89766           1                            None

In [8]:
gb = DataFrame(items.groupby(['movimiento'])); gb

   0                                                  1
0  1          fecha  nro_comprobante  movimiento nro...

Compra y Venta de Ganado

In [9]:
mov_gan = DataFrame(Movgan.objects.values('nro_novedad', 'fecha', 'entrada_salida', 'categoria__descripcion', 'total')); mov_gan

     nro_novedad       fecha  entrada_salida categoria__descripcion      total
0            337  2017-08-24               2                  Vacas    8977.00
1            337  2017-08-24               2                  Vacas   13038.00
2            421  2017-10-24               2                  Vacas   14190.00
3            421  2017-10-24               2                  Vacas   31244.00
4            421  2017-10-24               2                  Vacas    9680.00
5            421  2017-10-24               2                  Vacas   33908.00
6            421  2017-10-24               2                  Vacas    7567.00
7            481  2017-10-24               2                  Vacas   14190.00
8            481  2017-10-24               2                  Vacas   31244.00
9            481  2017-10-24               2                  Vacas    9680.00
10           481  2017-10-24               2                  Vacas   33908.00
11           481  2017-10-24               2                  Vacas    7567.00
12           562  2017-11-14               2            Vaquillonas  116610.00
13           562  2017-11-14               2             Novillitos   83850.00
14           542  2017-11-14               2                  Vacas   13325.00
15           542  2017-11-14               2                  Vacas   13860.00
16           612  2017-12-12               2                  Vacas   41860.00
17           612  2017-12-12               2                  Vacas   61020.00
18           612  2017-12-12               2                  Vacas   25086.00
19          8430  2016-01-12               2                  Vacas   10320.00
20          8430  2016-01-12               2             Novillitos  175750.00
21          8430  2016-01-12               2                  Vacas  210759.48
22          8597  2016-03-08               2                  Vacas   22185.00
23          8597  2016-03-08               2             Novillitos  159542.00
24          8859  2016-05-31               2             Novillitos  156240.00
25          8726  2016-05-13               2                  Vacas    5200.00
26          8684  2016-05-03               2                  Toros    8122.00
27          8684  2016-05-03               2                  Vacas   40896.00
28          8684  2016-05-03               2                  Vacas    2040.00
29          9049  2016-07-11               2                  Vacas   12320.00
30          9049  2016-07-11               2                  Vacas   20700.00
31          9049  2016-07-11               2                  Vacas    7392.00
32          9049  2016-07-11               2                  Vacas   10332.00
33          9211  2016-08-23               2                  Vacas   18084.00
34          9211  2016-08-23               2             Novillitos  175360.00
35           612  2017-12-12               2                  Vacas   13195.00
36           612  2017-12-12               2                  Vacas   18126.00
37           612  2017-12-12               2                  Vacas    8160.00
38           612  2017-12-12               2                  Vacas   10980.00
39           612  2017-12-12               2                  Vacas   42000.00
40           612  2017-12-12               2                  Vacas    5700.00
41           781  2018-02-06               2             Novillitos  187698.00
42           753  2018-02-06               2                  Vacas    6800.00
43           753  2018-02-06               2                  Vacas   39117.00
44           834  2018-03-01               2                  Vacas   13795.00
45           871  2018-03-01               2             Novillitos  153546.00
46           919  2018-04-05               2                  Vacas   13603.00
47           919  2018-04-05               2                  Vacas   18240.00
48           919  2018-04-05               2                  Vacas   11590.00
49           919  2018-04-05               2                  Vacas   56628.00
50          1015  2018-05-08               2             Novillitos  141034.00
51           997  2018-05-08               2                  Vacas    9620.00
52          9277  2016-09-20               2                  Vacas   32660.00
53          9277  2016-09-20               2                  Vacas   35100.00
54          9277  2016-09-20               2                  Vacas   10550.00
55          9277  2016-09-20               2             Novillitos  229658.00
56          9355  2016-10-24               2                  Vacas   18880.00
57          9355  2016-10-24               2                  Vacas   27213.00
58          9436  2016-11-15               2             Novillitos  130680.00
59          9436  2016-11-15               2             Novillitos  150405.00
60             1  2016-12-26               2                  Vacas  247500.00
61             2  2017-01-13               2             Novillitos  435840.00
62          9543  2017-01-12               2                  Vacas   55615.00
63          9543  2017-01-12               2                  Vacas   51538.00
64          9618  2017-02-07               2                  Vacas   11826.00
65          9618  2017-02-07               2                  Vacas   20570.00
66            13  2017-03-07               2                  Vacas   14413.00
67            13  2017-03-07               2                  Vacas   15232.00
68            13  2017-03-07               2                  Vacas    5760.00
69            13  2017-03-07               2                  Toros    7560.00
70          1316  2018-08-23               2                  Vacas    5600.00
71          1316  2018-08-23               2                  Vacas    4900.00
72          1403  2018-09-18               2                  Vacas   24640.00
73          1403  2018-09-18               2                  Vacas   16600.00
74          1403  2018-09-18               2                  Vacas   64872.00
75          1403  2018-09-18               2                  Vacas   12100.00
76          1500  2018-10-18               2                  Vacas   14260.00
77          1500  2018-10-18               2                  Vacas   14000.00
78          1500  2018-10-18               2                  Vacas   21120.00
79          1500  2018-10-18               2                  Vacas    7500.00
80          1500  2018-10-18               2                  Vacas    8910.00
81          1500  2018-10-18               2                  Vacas   13800.00
82          1558  2018-11-15               2                  Toros   27000.00
83          1558  2018-11-15               2                  Vacas   11932.00
84          1558  2018-11-15               2                  Vacas   56980.00
85          1675  2018-12-11               2             Novillitos  131040.00
86          1640  2018-12-11               2                  Vacas   15600.00
87           997  2018-05-08               2                  Vacas   46813.00
88          1127  2018-06-28               2                  Vacas   17490.00
89          1127  2018-06-28               2                  Vacas   14760.00
90          1127  2018-06-28               2                  Vacas   14750.00
91          1127  2018-06-28               2                  Vacas   19500.00
92          1127  2018-06-28               2                  Vacas   31200.00
93          1127  2018-06-28               2                  Vacas   26536.00
94          1127  2018-06-28               2                  Vacas   19950.00
95          1127  2018-06-28               2                  Toros   20002.00
96          1127  2018-06-28               2                  Vacas    9500.00
97          1127  2018-06-28               2                  Vacas    8170.00
98          1127  2018-06-28               2                  Vacas   11020.00
99          1127  2018-06-28               2                  Vacas    7990.00
100         1127  2018-06-28               2                  Vacas   35550.00
101         1164  2018-06-28               2             Novillitos  136080.00
102         1342  2018-08-23               2             Novillitos  118490.00
103         1316  2018-08-23               2                  Vacas   21300.00
104         1316  2018-08-23               2                  Vacas   14100.00
105         1316  2018-08-23               2                  Vacas   92160.00
106         8430  2016-01-12               2                  Toros    5700.00
107         8430  2016-01-12               2                  Vacas    8400.00
108         8430  2016-01-12               2                  Vacas   13794.00
109         8430  2016-01-12               2                  Vacas    7524.00
110         8430  2016-01-12               2                  Vacas    4080.00
111         8430  2016-01-12               2                  Vacas   10320.00
112         8430  2016-01-12               2             Novillitos  175750.00
113         8430  2016-01-12               2                  Toros    5700.00
114         8430  2016-01-12               2                  Vacas    8400.00
115         8430  2016-01-12               2                  Vacas   13794.00
116         8430  2016-01-12               2                  Vacas    7524.00
117         8430  2016-01-12               2                  Vacas    4080.00
118         1640  2018-12-11               2                  Vacas   72540.00
119         1694  2019-01-08               2                  Vacas   38070.00
120         1838  2019-03-12               2                  Vacas   23310.00
121         1838  2019-03-12               2                  Vacas   20412.00
122         1838  2019-03-12               2                  Vacas  122100.00
123         1897  2019-04-04               2                  Vacas   22032.00
124         1897  2019-04-04               2                  Vacas   18800.00
125         1897  2019-04-04               2                  Vacas   32340.00
126         1897  2019-04-04               2                  Vacas    3220.00
127         1980  2019-05-03               2                  Vacas   17760.00
128         1980  2019-05-03               2                  Vacas   30380.00
129         1980  2019-05-03               2                  Vacas   11340.00
130         1980  2019-05-03               2                  Vacas   11610.00
131         2061  2019-05-28               2                  Vacas   64395.00
132         2061  2019-05-28               2                  Vacas   26190.00
133         2061  2019-05-28               2                  Vacas   35700.00
134         2061  2019-05-28               2                  Vacas   12950.00
135         2095  2019-05-28               2                  Vacas   57600.00
136         2095  2019-05-28               2             Novillitos  214230.00
137           13  2017-03-07               2                  Toros    9940.00
138          141  2017-05-30               2             Novillitos   74018.00
139          141  2017-05-30               2             Novillitos   92070.00
140           65  2017-05-04               2                  Vacas    3840.00
141          100  2017-05-30               2                  Vacas    2160.00
142          100  2017-05-30               2                  Vacas    9460.00
143           34  2017-05-17               2                  Vacas    4840.00
144           34  2017-05-17               2                  Vacas    2160.00
145           34  2017-05-17               2                  Vacas   12900.00
146          194  2017-06-27               2                  Vacas    7650.00
147          194  2017-06-27               2                  Vacas    9288.00
148          194  2017-06-27               2                  Vacas   19740.00
149          194  2017-06-27               2                  Vacas   16800.00
150          194  2017-06-27               2                  Vacas    9699.00
151          271  2017-07-25               2                  Vacas    8232.00
152          271  2017-07-25               2                  Vacas   37179.00
153          359  2017-08-24               2             Novillitos  146890.00
154          337  2017-08-24               2                  Vacas   12064.00
155          337  2017-08-24               2                  Vacas   12354.00
156         2150  2019-06-25               2                  Vacas   30100.00
157         2150  2019-06-25               2                  Vacas   24400.00
158         2150  2019-06-25               2                  Vacas   22620.00
159         2150  2019-06-25               2                  Vacas   48670.00
160         2150  2019-06-25               2                  Vacas   67890.00
161         2150  2019-06-25               2                  Vacas    7830.00
162         2131  2019-06-25               2                  Vacas   31280.00
163         2131  2019-06-25               2                  Vacas   75075.00
164         2226  2019-07-23               2                  Toros   40180.00
165         2226  2019-07-23               2                  Vacas   16770.00
166         2226  2019-07-23               2                  Vacas   46200.00
167         2226  2019-07-23               2                  Vacas   53475.00
168         2226  2019-07-23               2                  Vacas  117290.00
169         2226  2019-07-23               2                  Vacas   14260.00
170         2351  2019-08-22               2                  Vacas    9345.00
171         2351  2019-08-22               2             Novillitos  127160.00
172         2351  2019-08-22               2             Novillitos   95850.00
173         2323  2019-08-22               2                  Vacas   32490.00
174         2323  2019-08-22               2                  Vacas   33550.00
175         2323  2019-08-22               2                  Vacas   31320.00
176         2323  2019-08-22               2                  Vacas   22790.00
177         2323  2019-08-22               2                  Vacas   33630.00
178         2323  2019-08-22               2                  Vacas   23460.00
179         2323  2019-08-22               2                  Vacas   56745.00
180         2323  2019-08-22               2                  Vacas   49350.00
181         2414  2019-09-17               2                  Vacas   35090.00
182         2414  2019-09-17               2                  Vacas   25725.00
183         2414  2019-09-17               2                  Vacas  156350.00
184         2414  2019-09-17               2                  Vacas   27825.00
185         2414  2019-09-17               2                  Vacas  118000.00
186         2414  2019-09-17               2                  Vacas   17020.00
187         2505  2019-10-22               2                  Vacas   40300.00
188         2505  2019-10-22               2                  Vacas   35400.00
189         2505  2019-10-22               2                  Vacas   33480.00
190         2505  2019-10-22               2                  Vacas  105000.00
191         2505  2019-10-22               2                  Vacas   53400.00
192         2505  2019-10-22               2                  Vacas   97200.00
193          111  2020-03-09               1             Novillitos       1.00
194           22  2020-03-09               1             Novillitos       1.00
195            1  2020-03-09               1            Vaquillonas     144.00
196            0  2020-03-09               1                  Vacas    1665.00

In [10]:
gb = DataFrame(mov_gan.groupby('entrada_salida').total.sum()); gb

                     total
entrada_salida
1                  1811.00
2               8420942.48

Movimientos de silos

In [11]:
mov_silos = DataFrame(MovSilos.objects.values('movimiento', 'fecha', 
                                              'nro_comprobante')); mov_silos

   movimiento       fecha  nro_comprobante
0           2  2019-05-15         12778688
1           2  2019-12-26             1255
2           2  2019-12-27         12778688
3           1  2020-03-09                0
4           1  2020-03-09                0
5           1  2020-03-09                0
6           2  2020-03-09                1
7           1  2020-03-09                1

In [12]:
gb = DataFrame(mov_silos.groupby(['movimiento'])); gb

   0                                                  1
0  1     movimiento       fecha  nro_comprobante
3  ...
1  2     movimiento       fecha  nro_comprobante
0  ...

Movimientos de leche

In [13]:
mov_prod = DataFrame(MovProd.objects.values('fecha', 'ing_egr', 'nro_comprob')); mov_prod

        fecha  ing_egr  nro_comprob
0  2019-07-01        2            0
1  2019-07-02        2            0
2  2020-03-09        2            1

In [14]:
gb = DataFrame(mov_prod.groupby(['ing_egr'])); gb

   0                                                  1
0  2          fecha  ing_egr  nro_comprob
0  2019-07...

In [15]:
ventas = DataFrame(Ventas.objects.values('fecha_comprob', 'nro_compro', 'imp_total', 'tipo_movim__descripcion')); ventas

    fecha_comprob  nro_compro   imp_total   tipo_movim__descripcion
0      2016-10-17          16   613337.80             Orden de Pago
1      2016-12-17          17   312984.80             Orden de Pago
2      2016-12-17          18   334408.03             Orden de Pago
3      2016-12-17          19   500000.00             Orden de Pago
4      2016-12-17          20   149863.12             Orden de Pago
5      2016-10-31        1605   697833.40  Factura Cuenta Corriente
6      2016-10-24        9355    47672.07  Factura Cuenta Corriente
7      2016-11-30          18   711796.80  Factura Cuenta Corriente
8      2016-11-15        9436   286068.10  Factura Cuenta Corriente
9      2017-03-24          29   481603.20             Orden de Pago
10     2017-03-24          30   108838.91             Orden de Pago
11     2017-03-24          31    47672.07             Orden de Pago
12     2017-03-31          90   400099.38  Factura Cuenta Corriente
13     2017-05-06          32   400099.38             Orden de Pago
14     2017-03-07          13    53048.32  Factura Cuenta Corriente
15     2017-03-07          13     4885.65           Nota de Crédito
16     2017-04-20          33    48162.67             Orden de Pago
17     2017-04-30         131   487663.72  Factura Cuenta Corriente
18     2018-09-18        1403    10800.83           Nota de Crédito
19     2018-09-29          79   122662.82             Orden de Pago
20     2018-10-01          80   117574.13             Orden de Pago
21     2018-10-06          81        0.01             Orden de Pago
22     2018-10-06          82    -1082.11             Orden de Pago
23     2018-09-30         785  1315198.20  Factura Cuenta Corriente
24     2018-10-27          83  1315198.20             Orden de Pago
25     2018-10-18        1500    86085.43  Factura Cuenta Corriente
26     2018-10-18        1500     8172.37           Nota de Crédito
27     2019-01-02          91   500000.00             Orden de Pago
28     2019-01-05          92    99423.47             Orden de Pago
29     2018-12-31         902  1614040.20  Factura Cuenta Corriente
30     2019-01-19          93  1114040.20             Orden de Pago
31     2016-06-30       62018    60000.00  Factura Cuenta Corriente
32     2016-06-01     6201604    60000.00  Factura Cuenta Corriente
33     2016-07-01     7201604   100000.00  Factura Cuenta Corriente
34     2016-08-31     8201604   120000.00  Factura Cuenta Corriente
35     2016-09-20     9201604   200000.00  Factura Cuenta Corriente
36     2018-01-20     1201804   200000.00  Factura Cuenta Corriente
37     2018-02-20     2201804   200000.00  Factura Cuenta Corriente
38     2018-03-20     3201804   200000.00  Factura Cuenta Corriente
39     2018-04-20     4201804   200000.00  Factura Cuenta Corriente
40     2018-05-20     5201804   200000.00  Factura Cuenta Corriente
41     2018-06-20     6201804   200000.00  Factura Cuenta Corriente
42     2018-07-20     7201804   200000.00  Factura Cuenta Corriente
43     2018-08-20     8201804   200000.00  Factura Cuenta Corriente
44     2018-09-20     9201804   200000.00  Factura Cuenta Corriente
45     2019-03-18          99   798933.50             Orden de Pago
46     2019-03-25         100   168200.10             Orden de Pago
47     2019-03-25         101   500000.00             Orden de Pago
48     2019-04-04        1897    84203.67  Factura Cuenta Corriente
49     2019-04-04        1897     9731.88           Nota de Crédito
50     2019-03-31        1025  1581597.60  Factura Cuenta Corriente
51     2019-04-17         102    74471.79             Orden de Pago
52     2019-04-27         103  1081597.60             Orden de Pago
53     2019-04-30        1070  1659208.20  Factura Cuenta Corriente
54     2019-07-11         114   184306.73             Orden de Pago
55     2019-07-12         115    19553.20             Orden de Pago
56     2019-06-30        1162  1826526.20  Factura Cuenta Corriente
57     2019-06-28         116   500000.00             Orden de Pago
58     2019-07-16         117  1326526.20             Orden de Pago
59     2019-07-23        2226   314663.06  Factura Cuenta Corriente
60     2019-07-30         118   600000.00             Orden de Pago
61     2019-07-31        1208  2091520.90  Factura Cuenta Corriente
62     2019-08-06         119   295875.50             Orden de Pago
63     2016-06-30        1450   530113.06  Factura Cuenta Corriente
64     2016-06-28     6237389   144310.14  Factura Cuenta Corriente
65     2016-06-02     6031414   107025.25  Factura Cuenta Corriente
66     2016-07-31        1488   565740.25  Factura Cuenta Corriente
67     2016-07-30     6470748    83072.63  Factura Cuenta Corriente
68     2016-07-11        9049    50434.41  Factura Cuenta Corriente
69     2016-08-31        1527   613337.80  Factura Cuenta Corriente
70     2016-08-23        9211   196719.97  Factura Cuenta Corriente
71     2016-11-26           2   456611.30             Orden de Pago
72     2018-05-31         632   846741.30  Factura Cuenta Corriente
73     2018-06-23          68   124662.00             Orden de Pago
74     2018-06-23          69   722079.30             Orden de Pago
75     2018-06-23          70   144912.62             Orden de Pago
76     2018-06-28        1127   258728.28  Factura Cuenta Corriente
77     2018-06-28        1127    21048.77           Nota de Crédito
78     2018-06-28        1164   149729.34  Factura Cuenta Corriente
79     2018-06-28        1164     8871.74           Nota de Crédito
80     2018-06-30         671   870434.44  Factura Cuenta Corriente
81     2017-06-27         194    68241.07  Factura Cuenta Corriente
82     2017-06-27         194     5721.07           Nota de Crédito
83     2017-07-29          39    62520.00             Orden de Pago
84     2017-07-31         247   822342.25  Factura Cuenta Corriente
85     2017-07-25         271    49962.34  Factura Cuenta Corriente
86     2017-07-25         271     2960.57           Nota de Crédito
87     2017-08-31         286   887077.20  Factura Cuenta Corriente
88     2017-09-30          40   887077.20             Orden de Pago
89     2017-09-30          41   822342.25             Orden de Pago
90     2017-10-24         481     6297.12           Nota de Crédito
91     2017-12-03          48    99963.75             Orden de Pago
92     2017-11-30         402  1001082.25  Factura Cuenta Corriente
93     2017-12-23          49  1001082.25             Orden de Pago
94     2017-11-14         542    29485.43  Factura Cuenta Corriente
95     2017-11-14         542     4534.83           Nota de Crédito
96     2017-11-14         562   218708.05  Factura Cuenta Corriente
97     2017-11-14         562    13068.99           Nota de Crédito
98     2017-12-23          50   205639.06             Orden de Pago
99     2018-02-24          57   238050.25             Orden de Pago
100    2018-03-01         834    14956.95  Factura Cuenta Corriente
101    2018-03-01         834     4214.37           Nota de Crédito
102    2018-03-01         871   167994.52  Factura Cuenta Corriente
103    2018-03-01         871    10010.43           Nota de Crédito
104    2018-02-28         517   681864.10  Factura Cuenta Corriente
105    2018-03-17          58    10742.58             Orden de Pago
106    2018-03-17          59   157984.10             Orden de Pago
107    2018-03-17          60   681883.44             Orden de Pago
108    2016-12-27          21   286068.10             Orden de Pago
109    2016-12-27          22   697833.40             Orden de Pago
110    2016-12-27          23   711796.80             Orden de Pago
111    2016-12-26           1   273487.50  Factura Cuenta Corriente
112    2016-12-31          56   708102.80  Factura Cuenta Corriente
113    2017-01-31          16   546712.40  Factura Cuenta Corriente
114    2017-01-13           2   481603.20  Factura Cuenta Corriente
115    2017-01-12        9543   108838.91  Factura Cuenta Corriente
116    2017-02-28          55   409289.16  Factura Cuenta Corriente
117    2017-02-07        9618    32537.38  Factura Cuenta Corriente
118    2017-03-24          24   409289.16             Orden de Pago
119    2017-03-24          25    32537.38             Orden de Pago
120    2017-03-24          26   708102.80             Orden de Pago
121    2017-03-24          27   546712.40             Orden de Pago
122    2017-03-24          28   273487.50             Orden de Pago
123    2018-07-11          71   237679.52             Orden de Pago
124    2018-07-16          72   870434.44             Orden de Pago
125    2018-07-04          73   140857.60             Orden de Pago
126    2018-07-31         709  1023228.56  Factura Cuenta Corriente
127    2018-08-02          74   150870.00             Orden de Pago
128    2018-08-09          75   100000.00             Orden de Pago
129    2018-08-16          76   772358.56             Orden de Pago
130    2018-08-23        1316   152160.94  Factura Cuenta Corriente
131    2018-08-23        1316    12094.82           Nota de Crédito
132    2018-08-23        1342   130387.78  Factura Cuenta Corriente
133    2018-08-23        1342     7724.96           Nota de Crédito
134    2018-09-05          77   140066.12             Orden de Pago
135    2018-08-31         747  1196828.60  Factura Cuenta Corriente
136    2018-09-15          78  1196828.60             Orden de Pago
137    2018-09-18        1403   128374.96  Factura Cuenta Corriente
138    2017-08-24         337    51223.70  Factura Cuenta Corriente
139    2017-08-24         337     4905.70           Nota de Crédito
140    2017-08-24         359   161231.80  Factura Cuenta Corriente
141    2017-08-24         359     9576.49           Nota de Crédito
142    2017-09-30          42    47001.77             Orden de Pago
143    2017-09-30          43    46318.00             Orden de Pago
144    2017-09-30          44   151655.30             Orden de Pago
145    2017-09-30         324   990162.25  Factura Cuenta Corriente
146    2017-10-21          45   990163.25             Orden de Pago
147    2017-10-24         421   106260.87  Factura Cuenta Corriente
148    2017-10-24         421     6297.12           Nota de Crédito
149    2017-11-28          46    99963.75             Orden de Pago
150    2017-10-31         363  1082717.10  Factura Cuenta Corriente
151    2017-11-28          47  1082717.10             Orden de Pago
152    2017-10-24         481   106260.87  Factura Cuenta Corriente
153    2018-10-27          84    77913.06             Orden de Pago
154    2018-11-15        1558   105676.46  Factura Cuenta Corriente
155    2018-11-15        1558     6252.99           Nota de Crédito
156    2018-10-31         824  1526034.60  Factura Cuenta Corriente
157    2018-12-11        1640    97091.48  Factura Cuenta Corriente
158    2018-12-11        1640     9945.29           Nota de Crédito
159    2018-12-11        1675   143996.27  Factura Cuenta Corriente
160    2018-12-11        1675     8543.15           Nota de Crédito
161    2018-12-29          85    87146.19             Orden de Pago
162    2018-12-29          86   135453.12             Orden de Pago
163    2018-12-29          87    99423.47             Orden de Pago
164    2018-11-16          88  1526034.60             Orden de Pago
165    2018-11-30         863  1617268.00  Factura Cuenta Corriente
166    2018-12-03          89   500000.00             Orden de Pago
167    2018-12-18          90  1117268.00             Orden de Pago
168    2016-11-26           3   378724.94             Orden de Pago
169    2016-11-26           4   390800.78             Orden de Pago
170    2016-11-26           5    90000.00             Orden de Pago
171    2016-11-26           6   183437.81             Orden de Pago
172    2016-11-26           7    50731.53             Orden de Pago
173    2016-11-26           8     5271.89             Orden de Pago
174    2016-11-26           9   159202.94             Orden de Pago
175    2016-11-26          10   196719.97             Orden de Pago
176    2016-11-26          11   403336.20             Orden de Pago
177    2016-11-26          12   546688.00             Orden de Pago
178    2016-11-26          13   530113.06             Orden de Pago
179    2016-11-26          14   565740.25             Orden de Pago
180    2016-11-26          15    50434.41             Orden de Pago
181    2016-09-30        1566   649863.10  Factura Cuenta Corriente
182    2016-09-20        9277   312984.80  Factura Cuenta Corriente
183    2016-10-20    10201604   250000.00  Factura Cuenta Corriente
184    2016-11-20    11201604   250000.00  Factura Cuenta Corriente
185    2016-12-20    12201604   250000.00  Factura Cuenta Corriente
186    2017-01-20     1201704   220000.00  Factura Cuenta Corriente
187    2017-02-20     2201704   170000.00  Factura Cuenta Corriente
188    2017-03-20     3201704   150000.00  Factura Cuenta Corriente
189    2017-04-20     4201704   190000.00  Factura Cuenta Corriente
190    2017-05-20     5201704   200000.00  Factura Cuenta Corriente
191    2017-06-20     6201704   200000.00  Factura Cuenta Corriente
192    2017-07-20     7201704   150000.00  Factura Cuenta Corriente
193    2017-08-20     8201704   170000.00  Factura Cuenta Corriente
194    2017-09-20     9201704   170000.00  Factura Cuenta Corriente
195    2017-10-20    10201704   200000.00  Factura Cuenta Corriente
196    2017-11-20    11201704   200000.00  Factura Cuenta Corriente
197    2017-12-20    12201704   200000.00  Factura Cuenta Corriente
198    2018-04-04          61    50000.00             Orden de Pago
199    2018-04-05          62   155764.00             Orden de Pago
200    2018-03-31         555   780912.44  Factura Cuenta Corriente
201    2018-03-31          14   103412.91           Nota de Crédito
202    2018-04-28          64   678562.40             Orden de Pago
203    2018-04-05         919   108274.55  Factura Cuenta Corriente
204    2018-04-05         919     8954.48           Nota de Crédito
205    2018-04-18          65    99320.07             Orden de Pago
206    2018-04-30         593   787889.30  Factura Cuenta Corriente
207    2018-06-02          66   787889.30             Orden de Pago
208    2018-05-08         997    62024.00  Factura Cuenta Corriente
209    2018-05-08         997     3679.15           Nota de Crédito
210    2018-05-08        1015   154107.34  Factura Cuenta Corriente
211    2018-05-08        1015     9194.72           Nota de Crédito
212    2018-06-16          67    58344.85             Orden de Pago
213    2018-10-20    10201804   200000.00  Factura Cuenta Corriente
214    2018-11-20    11201804   300000.00  Factura Cuenta Corriente
215    2018-12-20    12201804   200000.00  Factura Cuenta Corriente
216    2019-01-20     1201904   200000.00  Factura Cuenta Corriente
217    2019-01-26          94  6210000.00             Orden de Pago
218    2019-01-08        1694    41360.18  Factura Cuenta Corriente
219    2019-01-08        1694     2481.97           Nota de Crédito
220    2019-02-02          95    38878.21             Orden de Pago
221    2019-01-31         943  1492425.80  Factura Cuenta Corriente
222    2019-02-05          96   500000.00             Orden de Pago
223    2019-02-18          97   992425.75             Orden de Pago
224    2019-03-02          98   500000.00             Orden de Pago
225    2019-03-12        1838   182160.11  Factura Cuenta Corriente
226    2019-03-12        1838    13960.02           Nota de Crédito
227    2019-02-28         983  1295654.00  Factura Cuenta Corriente
228    2019-05-02         104   500000.00             Orden de Pago
229    2019-05-16         105  1159208.20             Orden de Pago
230    2019-05-03        1980    76853.08  Factura Cuenta Corriente
231    2019-05-15    12778688  1978058.80  Factura Cuenta Corriente
232    2019-05-16         106    72218.37             Orden de Pago
233    2019-05-31         107  1978058.80             Orden de Pago
234    2019-05-28        2061   153293.69  Factura Cuenta Corriente
235    2019-05-28        2095   293666.16  Factura Cuenta Corriente
236    2019-05-31        1116  1833863.40  Factura Cuenta Corriente
237    2019-06-25        2150   220754.38  Factura Cuenta Corriente
238    2019-05-28         108   500000.00             Orden de Pago
239    2019-06-13         109  1333863.40             Orden de Pago
240    2019-06-10         110   187223.34             Orden de Pago
241    2019-06-10         111    13237.36             Orden de Pago
242    2019-07-05         113   214230.00             Orden de Pago
243    2017-05-27          34   487663.72             Orden de Pago
244    2017-05-17          34    21806.87  Factura Cuenta Corriente
245    2017-05-17          34     3175.88           Nota de Crédito
246    2017-05-04          65     4217.87  Factura Cuenta Corriente
247    2017-05-04          65      250.35           Nota de Crédito
248    2017-05-30         100    12766.67  Factura Cuenta Corriente
249    2017-05-30         100     3188.57           Nota de Crédito
250    2017-05-30         141   181440.06  Factura Cuenta Corriente
251    2017-05-30         141    10828.10           Nota de Crédito
252    2017-05-31         169   604998.20  Factura Cuenta Corriente
253    2017-07-08          35   604998.20             Orden de Pago
254    2017-07-08          36   170611.95             Orden de Pago
255    2017-07-08          37    32176.61             Orden de Pago
256    2017-06-30         208   769283.90  Factura Cuenta Corriente
257    2017-07-29          38   769283.90             Orden de Pago
258    2017-12-23          51    24950.60             Orden de Pago
259    2017-12-15     9604304   670847.10  Factura Cuenta Corriente
260    2017-12-30          52   670847.10             Orden de Pago
261    2017-12-12         612   244675.40  Factura Cuenta Corriente
262    2017-12-12         612    17504.85           Nota de Crédito
263    2017-12-30          53   227170.56             Orden de Pago
264    2017-12-31         440   863463.50  Factura Cuenta Corriente
265    2018-01-16          54   863463.50             Orden de Pago
266    2018-01-31         479   833160.75  Factura Cuenta Corriente
267    2018-02-06         781   204949.12  Factura Cuenta Corriente
268    2018-02-06         781    12236.97           Nota de Crédito
269    2018-02-06         753    50541.65  Factura Cuenta Corriente
270    2018-02-06         753     5203.56           Nota de Crédito
271    2018-02-24          55   833160.75             Orden de Pago
272    2018-02-24          56       -0.99             Orden de Pago
273    2019-08-20         120  1491520.90             Orden de Pago
274    2019-08-22        2323   311316.88  Factura Cuenta Corriente
275    2019-08-22        2351   250790.08  Factura Cuenta Corriente
276    2019-08-31        1254  2452555.50  Factura Cuenta Corriente
277    2019-09-04         121   272581.62             Orden de Pago
278    2019-09-05         122    27480.41             Orden de Pago
279    2019-08-29         123   600000.00             Orden de Pago
280    2019-09-17        2414   415891.12  Factura Cuenta Corriente
281    2019-09-16         124  1852555.50             Orden de Pago
282    2019-10-02         125   223011.30             Orden de Pago
283    2019-10-10         126   391116.38             Orden de Pago
284    2019-09-30        1302  2695217.80  Factura Cuenta Corriente
285    2019-09-30         127   600000.00             Orden de Pago
286    2019-10-16         128  2095217.80             Orden de Pago
287    2019-10-22        2505   399393.12  Factura Cuenta Corriente
288    2019-10-31         129   800000.00             Orden de Pago
289    2019-10-31        1349  2929064.80  Factura Cuenta Corriente
290    2019-12-26        1255   457278.06  Factura Cuenta Corriente
291    2019-12-27    12778688  1926730.10  Factura Cuenta Corriente
292    2016-01-31       25447   439058.56  Factura Cuenta Corriente

In [24]:
costos = movimpu_df[movimpu_df.imputacion_acumulada.isin(
    impu_ganado)].importe.sum()
ventas = movimpu_df[movimpu_df.imputacion_acumulada.isin(
    venta_ganado)].importe.sum()
utilidad_neta = ventas - costos
utilidad = utilidad_neta / ventas
ganado = {
    'ventas': ventas,
    'costos': costos,
    'utilidad_neta': utilidad_neta,
    'utilidad': utilidad,
}

costos = movimpu_df[movimpu_df.imputacion_acumulada.isin(
    impu_agriculura)].importe.sum()
ventas = movimpu_df[movimpu_df.imputacion_acumulada.isin(
    venta_agriculura)].importe.sum()
utilidad_neta = ventas - costos
utilidad = utilidad_neta / ventas
agricultura = {
    'ventas': ventas,
    'costos': costos,
    'utilidad_neta': utilidad_neta,
    'utilidad': utilidad,
}

costos = movimpu_df[movimpu_df.imputacion_acumulada.isin(
    impu_tambo)].importe.sum()
ventas = movimpu_df[movimpu_df.imputacion_acumulada.isin(
    venta_tambo)].importe.sum()
utilidad_neta = ventas - costos
utilidad = utilidad_neta / ventas
tambo = {
    'ventas': ventas,
    'costos': costos,
    'utilidad_neta': utilidad_neta,
    'utilidad': utilidad,
}

rentabilidad = {
    'categoria': ['Ganado', 'Agricultura', 'Tambo'],
    'utilidad': [ganado['utilidad'], agricultura['utilidad'], tambo['utilidad']]
}

df = DataFrame(rentabilidad)
df.loc[df.utilidad < 0, 'color'] = 'red'
df.loc[df.utilidad > 0, 'color'] = 'green'
percentage = abs(df.utilidad) / abs(df.utilidad).sum() * 100
df['percentage'] = round(percentage, 1)
df['angle'] = abs(df.utilidad) / abs(df.utilidad).sum() * 2 * pi
source = ColumnDataSource(df)
source.data['percentage'] = [f'{x}%' for x in
                             source.data['percentage']]

tooltips = [("Categoría", "@categoria"),
            ("Utilidad", "@utilidad{$0,0.00}"),
            ('% del total', '@percentage')]
hovertool = HoverTool(names=['wedge'], tooltips=tooltips)
plot = figure(
    tools=["tap,reset,save", hovertool],
    toolbar_location='above', height=300)
plot.wedge(x=0, y=0, radius=0.4,
           start_angle=cumsum('angle', include_zero=True),
           end_angle=cumsum('angle'),
           line_color='white', line_width=0.4, 
           fill_color='color',
           legend_field='categoria',
           source=source, name='wedge')
show(plot)

In [19]:
source.data

{'index': array([0, 1, 2]),
 'categoria': array(['Ganado', 'Agricultura', 'Tambo'], dtype=object),
 'importe': array([ 0.66884054, -0.38542257,  0.66276966]),
 'percentage': ['70.7%', '-40.7%', '70.0%'],
 'angle': array([ 4.44145424, -2.55940934,  4.40114041])}